version: '3.8'

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: 'true'
      ORACLE_DISABLE_ASYNCH_IO: 'true'
      ORACLE_PASSWORD: 'Secure@Pwa9'
    volumes:
      - oracle-data:/u01/app/oracle

  redis:
    image: redis:6.0
    container_name: redis
    ports:
      - "6379:6379"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
#    container_name: app.jar
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle-db:1521:xe
#                             jdbc:oracle:thin:@localhost:8090:XE
      SPRING_DATASOURCE_USERNAME: C##test_user
      SPRING_DATASOURCE_PASSWORD: Secure@Pwa9
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - oracle-db
      - redis
    networks:
      - my_network

networks:
  my_network:

volumes:
  oracle-data: